### ISSUE TITLE
[Feature] Better Commit Experience

### ISSUE THREAD

**Issue by 5ouma** [Roytangrb/gitwok#4]
### Is your feature request related to a problem? Please describe.
1. See the detail of each type.
2. Disable `[Enter 2 empty lines to finish]`.
3. Interactive `git commit`.

### Describe the solution you'd like
1. Specify types and their explanations on `gitwok.yaml`
```yaml
gitwok:
  commit:
    type:
      - type1
        detail: detail of type1
      - type2
        detail: detail of type2
```

2. Specify whether to write multiple lines on `gitwok.yaml`.
```yaml
gitwok:
  commit:
    prompt:
      multiple-lines: false
```

3. I use [Gitlint](https://github.com/jorisroovers/gitlint), and it shows interactive questions about whether to ignore warnings, not to commit, or to edit the commit message.
  Since GitWok prevents it from showing the questions, the `git commit` command never ends with Gitlint waiting for my answer.
